<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIyF1H0Y\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIyF1H0Y/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerIyF1H0Y.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerIyF1H0Y\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerIyF1H0Y\App_KernelTestDebugContainer([
    'container.build_hash' => 'IyF1H0Y',
    'container.build_id' => 'bba83132',
    'container.build_time' => 1594889995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIyF1H0Y');
