<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUf6ZVfo\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUf6ZVfo/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUf6ZVfo.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUf6ZVfo\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerUf6ZVfo\App_KernelTestDebugContainer([
    'container.build_hash' => 'Uf6ZVfo',
    'container.build_id' => 'e6a328a7',
    'container.build_time' => 1594889216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUf6ZVfo');
