<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsw3T24\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsw3T24/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBsw3T24.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBsw3T24\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBsw3T24\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bsw3T24',
    'container.build_id' => '7322eb4b',
    'container.build_time' => 1594812670,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsw3T24');
