<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC3EdtN3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC3EdtN3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC3EdtN3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC3EdtN3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC3EdtN3\App_KernelDevDebugContainer([
    'container.build_hash' => 'C3EdtN3',
    'container.build_id' => 'f8a6a5ff',
    'container.build_time' => 1594888246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC3EdtN3');
