<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkfn0Cs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkfn0Cs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkfn0Cs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkfn0Cs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFkfn0Cs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fkfn0Cs',
    'container.build_id' => 'cfbdd6eb',
    'container.build_time' => 1594898615,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkfn0Cs');
